[package]
name = "server-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-mem-server = { path = "../../crates/agent-mem-server" }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
