[package]
name = "phase4-demo"
version = "2.0.0"
edition = "2021"
description = "Phase 4 Performance and Scalability Demo"

[dependencies]
# AgentMem dependencies
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
agent-mem-core = { path = "../../crates/agent-mem-core" }
agent-mem-performance = { path = "../../crates/agent-mem-performance" }

# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Time handling
chrono = { workspace = true }

# UUID generation
uuid = { workspace = true, features = ["v4"] }

[[bin]]
name = "performance_demo"
path = "src/main.rs"
